//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buoi_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string DVTinh { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string MaLoai { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
